### ISSUE TITLE
feat(artifacts): generate mock `AuxParams` for future download flow

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#52]
## Tasks
- [ ] Crate small Rust bin that imports the `proofs` crate from `web-prover` to generate `PublicParams`
- [ ] For each given `*b` build, create `PublicParams` for it
- [ ] Serialize and compress to get offline-storable `AuxParams`
- [ ] Create/edit workflow to have this output with corresponding circuits
- [ ] Remove unneeded circuits

--- 

## Unknowns
- Do we want to have this instead created for ALL circuits we generate (so mixing together 512b and 1024b)? It is possible if we do that then we can still just dispatch the circuits we want as we need, but every release will only need one `PublicParams`.
