### ISSUE TITLE
feat: encryption circuit verifies ciphertext hash from `step_in`

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#53]
## Tasks
We need to validate that we encrypt to the correct ciphertext, i.e., the same ciphertext the proxy signed. Therefore, this needs to come into the NIVC chain as a public input. To solve this we can do:
- [ ] AES (as well as pending ChaCha20) expect `step_in` to be a hash of the ciphertext.
- [ ] Hash will be computed outside of circuit in the same way that `DataHasher` does. 
- [ ] We need to assert after all encryption circuits have ran (that is, all plaintext has been encrypted), that we do end up with a hash match. This can likely be done efficiently by checking the hash in each fold and noting that we will eventually get a hash match on the final circuit.

The exact architecture here hasn't been totally decided.
