### ISSUE TITLE
feat: foldable ChaCha20 circuit

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#54]
## Tasks
ChaCha20 is likely quite a bit more efficient than AES-GCTR. We should implement a ChaCha20 circuit that can be a drop in replacement for AES-GCTR.
- [x] Implement ChaCha20 algorithm
- [x] Create circuit allowing adaptable amounts of 32bit words to be passed to ChaCha20
- [x] Create NIVC circuit that integrates with the HTTP/JSON NIVC chain *a-la* AES-GCTR-NIVC.

**Comment by Autoparallel** [comment]
Attached medium priority since this is a big speed boost, but not immediately needed for testnet launch. Though, it may be. Time will tell.
