### ISSUE TITLE
ci: split up artifacts into sizes and prover/verifier data

### ISSUE THREAD

**Issue by Autoparallel** [pluto/web-prover-circuits#62]
## Tasks
- [ ] Split up artifacts to build into different zip files for different sizes (e.g., 512b and 1024b)
- [ ] Further split up into two components for each:
    - [ ] A "prover" portion which has the R1CS, witness generation, and prover key
    - [ ] A "verifier" portion which should just have the verifier key
